"""Importer for OpenAPI specs generated by openapi-llm browser extension."""

import json
from pathlib import Path
from typing import Dict, Any, Optional

try:
    from prance import ResolvingParser
    HAS_PRANCE = True
except ImportError:
    HAS_PRANCE = False
    ResolvingParser = None


class OpenAPILLMImporter:
    """Imports and enhances OpenAPI specs generated by openapi-llm."""
    
    @staticmethod
    def import_browser_spec(spec_path: str) -> Dict[str, Any]:
        """
        Import spec from openapi-llm with LLM-generated descriptions.
        
        Args:
            spec_path: Path to the JSON spec generated by openapi-llm
            
        Returns:
            Resolved OpenAPI specification dictionary
        """
        with open(spec_path, 'r') as f:
            spec = json.load(f)
        
        # Enhance with LLM descriptions (already included by openapi-llm)
        # The x-llm-intent field contains natural language descriptions
        if "paths" in spec:
            for path, methods in spec["paths"].items():
                for method, operation in methods.items():
                    if method.upper() in ["GET", "POST", "PUT", "DELETE", "PATCH"]:
                        # Combine existing descriptions with LLM intent
                        summary = operation.get("summary", "")
                        description = operation.get("description", "")
                        llm_intent = operation.get("x-llm-intent", "")
                        
                        # Create enhanced description for better matching
                        enhanced_desc = f"{summary} {description} {llm_intent}".strip()
                        operation["x-enhanced-description"] = enhanced_desc
        
        # Resolve if prance is available
        if HAS_PRANCE:
            parser = ResolvingParser(spec_string=json.dumps(spec))
            return parser.specification
        else:
            return spec
    
    @staticmethod
    def from_browser_session(session_id: str, base_url: str = "https://openapi-llm.superflows.ai") -> str:
        """
        Get spec URL from openapi-llm API session.
        
        Args:
            session_id: Session ID from openapi-llm browser extension
            base_url: Base URL for openapi-llm API
            
        Returns:
            URL to fetch the spec JSON
        """
        return f"{base_url}/sessions/{session_id}/spec.json"
    
    @staticmethod
    def is_llm_enhanced(spec: Dict[str, Any]) -> bool:
        """
        Check if the spec contains LLM-generated descriptions.
        
        Args:
            spec: OpenAPI specification dictionary
            
        Returns:
            True if spec has x-llm-intent fields
        """
        if "paths" not in spec:
            return False
        
        for path, methods in spec["paths"].items():
            for method, operation in methods.items():
                if "x-llm-intent" in operation:
                    return True
        
        return False
    
    @staticmethod
    def extract_llm_descriptions(spec: Dict[str, Any]) -> Dict[str, str]:
        """
        Extract all LLM-generated descriptions from the spec.
        
        Args:
            spec: OpenAPI specification dictionary
            
        Returns:
            Dictionary mapping endpoints to LLM descriptions
        """
        descriptions = {}
        
        if "paths" not in spec:
            return descriptions
        
        for path, methods in spec["paths"].items():
            for method, operation in methods.items():
                if method.upper() in ["GET", "POST", "PUT", "DELETE", "PATCH"]:
                    endpoint = f"{method.upper()} {path}"
                    llm_intent = operation.get("x-llm-intent", "")
                    enhanced = operation.get("x-enhanced-description", "")
                    
                    if llm_intent or enhanced:
                        descriptions[endpoint] = enhanced or llm_intent
        
        return descriptions
