flowchart LR
    subgraph src__propact
        src__propact__enhanced__Propact__send_to_endpoint["send_to_endpoint"]
        src__propact__converter__MDConverter___text_to_markdown["_text_to_markdown"]
        src__propact__converter__MDConverter__extract_from_markdown["extract_from_markdown"]
        src__propact__converter__MDConverter___prepare_form_payload["_prepare_form_payload"]
        src__propact__converter__MDConverter___binary_to_markdown["_binary_to_markdown"]
        src__propact__converter__MDConverter__response_to_markdown["response_to_markdown"]
        src__propact__enhanced__Propact___smart_split_md["_smart_split_md"]
        src__propact__cli__main["main"]
        src__propact__converter__MDConverter___dict_to_markdown["_dict_to_markdown"]
        src__propact__converter__MDConverter__prepare_payload["prepare_payload"]
        src__propact__converter__MDConverter___prepare_openapi_payload["_prepare_openapi_payload"]
        src__propact__cli__display_results["display_results"]
        src__propact__converter__MDConverter___prepare_multipart_payload["_prepare_multipart_payload"]
        src__propact__converter__MDConverter___prepare_json_payload["_prepare_json_payload"]
        src__propact__converter__MDConverter__embed_media["embed_media"]
        src__propact__converter__MDConverter___get_mime_type["_get_mime_type"]
    end
    src__propact__cli__main --> src__propact__cli__display_results
    src__propact__enhanced__Propact___smart_split_md --> src__propact__converter__MDConverter__extract_from_markdown
    src__propact__enhanced__Propact___smart_split_md --> src__propact__converter__MDConverter__prepare_payload
    src__propact__enhanced__Propact__send_to_endpoint --> src__propact__converter__MDConverter__prepare_payload
    src__propact__enhanced__Propact__send_to_endpoint --> src__propact__converter__MDConverter__response_to_markdown
    src__propact__converter__MDConverter__response_to_markdown --> src__propact__converter__MDConverter___binary_to_markdown
    src__propact__converter__MDConverter__response_to_markdown --> src__propact__converter__MDConverter___dict_to_markdown
    src__propact__converter__MDConverter__response_to_markdown --> src__propact__converter__MDConverter___text_to_markdown
    src__propact__converter__MDConverter__prepare_payload --> src__propact__converter__MDConverter___prepare_openapi_payload
    src__propact__converter__MDConverter__prepare_payload --> src__propact__converter__MDConverter___prepare_multipart_payload
    src__propact__converter__MDConverter__prepare_payload --> src__propact__converter__MDConverter___prepare_json_payload
    src__propact__converter__MDConverter__prepare_payload --> src__propact__converter__MDConverter___prepare_form_payload
    src__propact__converter__MDConverter___prepare_openapi_payload --> src__propact__converter__MDConverter___prepare_json_payload
    src__propact__converter__MDConverter__embed_media --> src__propact__converter__MDConverter___get_mime_type
